[package]
name = "rurl"
version = "0.1.0"
authors = ["marilla"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.2"
reqwest = "0.9.21"